<?php

/**
 * Created by PhpStorm.
 * User: max2thousand
 * Date: 09/03/15
 * Time: 11:04
 */
define('DATATXT_DEFAULT_ENDPOINT', 'https://api.dandelion.eu');
define('IS_DATATXT_PREFIX', 'datatxt_api_integration_is_datatxt_taxonomy_');
define('DATATXT_LANGUAGE_PREFIX', 'datatxt_api_integration_language_');
define('DATATXT_ENTITY_EXTRACTION_MIN_CHARS', 150);
define('DATATXT_CLASSIFICATION_SCORE_MULTIPLIER', .423);
define('DATATXT_ENTITY_EXTRACTION_SCORE_MULTIPLIER', 1.18);
